# Generated by Django 5.2.15 on 2026-06-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_populate_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(default='B.E.', max_length=50),
        ),
    ]
