# Generated by Django 5.2.15 on 2026-06-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_studentprofile_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_ac',
            field=models.BooleanField(default=False),
        ),
    ]
