# Generated by Django 5.2.15 on 2026-06-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_room_is_ac'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='batch',
            field=models.CharField(default='2022 to 2026', max_length=20),
        ),
    ]
