# Generated by Django 5.2.15 on 2026-06-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_studentprofile_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomallocation',
            name='bed_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
