# Generated by Django 5.2.15 on 2026-06-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_roomallocation_bed_number_alter_room_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('SINGLE', 'Single Sharing'), ('DOUBLE', 'Double Sharing'), ('TRIPLE', 'Triple Sharing'), ('FOUR', 'Four Sharing')], default='SINGLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='roomchangerequest',
            name='preferred_room_type',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single Sharing'), ('DOUBLE', 'Double Sharing'), ('TRIPLE', 'Triple Sharing'), ('FOUR', 'Four Sharing')], max_length=10, null=True),
        ),
    ]
