# Generated by Django 5.2.15 on 2026-06-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_alter_room_room_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='yearly_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
