# Generated by Django 5.2.15 on 2026-06-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_room_yearly_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_photo',
            field=models.ImageField(blank=True, null=True, upload_to='room_photos/'),
        ),
    ]
